export const APPLIED_DESIGN_REQUEST = 'APPLIED_DESIGN_REQUEST'
export const APPLIED_DESIGN_SUCCESS = 'APPLIED_DESIGN_SUCCESS'
export const APPLIED_DESIGN_FAIL = 'APPLIED_DESIGN_FAIL'
export const SET_APPLIED_DEISGN = 'SET_APPLIED_DEISGN'