export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const DESIGN_LIST_REQUEST = 'DESIGN_LIST_REQUEST'
export const DESIGN_LIST_SUCCESS = 'DESIGN_LIST_SUCCESS'
export const DESIGN_LIST_FAIL = 'DESIGN_LIST_FAIL'

export const DESIGN_DETAILS_REQUEST = 'DESIGN_DETAILS_REQUEST'
export const DESIGN_DETAILS_SUCCESS = 'DESIGN_DETAILS_SUCCESS'
export const DESIGN_DETAILS_FAIL = 'DESIGN_DETAILS_FAIL'
