# Generated by Django 5.1 on 2026-08-05 09:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewName', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('name', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('material', models.CharField(max_length=50, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VinylColor',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rgb_Code', models.CharField(max_length=7, null=True)),
                ('show', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('show', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('design_Category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designcategory')),
                ('design_Type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(max_length=40, null=True)),
                ('taxPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isReady', models.BooleanField(default=False)),
                ('readyAt', models.DateTimeField(null=True)),
                ('isShipped', models.BooleanField(default=False)),
                ('shippedAt', models.DateTimeField(null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='PickedDesign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.design')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdDesign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pickeddesign')),
                ('orderItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderitem')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designplace')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color_Name', models.CharField(max_length=30, null=True)),
                ('color_RGB', models.CharField(max_length=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('show', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('size', models.CharField(max_length=15, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('countInStock', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('productColor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productcolor')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productColorSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolorsize'),
        ),
        migrations.CreateModel(
            name='ProductDesignPlace',
            fields=[
                ('x_start', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('x_end', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('y_start', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('y_end', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('_id', models.AutoField(default=datetime.datetime.now, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('viewName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.designplace')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('image', models.ImageField(null=True, upload_to='')),
                ('_id', models.AutoField(default=None, editable=False, primary_key=True, serialize=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productcolor')),
                ('viewName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productdesignplace')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image', models.ImageField(null=True, unique=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('shippingPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('emailAddress', models.CharField(max_length=50, null=True)),
                ('phoneNo', models.CharField(blank=True, max_length=20, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='DesignComponent',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('x_start', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('x_end', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('y_start', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('y_end', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('is_color_changeable', models.BooleanField(default=True)),
                ('pickedDesign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pickeddesign')),
                ('component_color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vinylcolor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('product', 'color_Name'), name='unique_product_color'),
        ),
        migrations.AddConstraint(
            model_name='productcolorsize',
            constraint=models.UniqueConstraint(fields=('productColor', 'size'), name='unique_productColor_size'),
        ),
        migrations.AddConstraint(
            model_name='productcolorimage',
            constraint=models.UniqueConstraint(fields=('color', 'viewName'), name='unique_color_viewName'),
        ),
    ]
