# Generated by Django 5.1 on 2024-09-02 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('name', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VinylColor',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rgb_Code', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('show', models.BooleanField(default=True)),
                ('design_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.designtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(max_length=40, null=True)),
                ('taxPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color_Name', models.CharField(max_length=30, null=True)),
                ('color_RGB', models.CharField(max_length=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('image', models.ImageField(null=True, upload_to='')),
                ('viewName', models.CharField(max_length=50, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('size', models.CharField(max_length=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('countInStock', models.DecimalField(decimal_places=0, max_digits=7)),
                ('productColor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=7, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('productColorSize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolorsize')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesignPlace',
            fields=[
                ('place', models.CharField(max_length=20, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image', models.ImageField(null=True, upload_to='')),
                ('viewName', models.CharField(max_length=50, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProdDesign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.design')),
                ('orderItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderitem')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productdesignplace')),
                ('designColor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vinylcolor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('product', 'color_Name'), name='unique_product_color'),
        ),
        migrations.AddConstraint(
            model_name='productcolorimage',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'viewName'), name='unique_product_color_viewName'),
        ),
        migrations.AddConstraint(
            model_name='productcolorsize',
            constraint=models.UniqueConstraint(fields=('productColor', 'size'), name='unique_productColor_size'),
        ),
        migrations.AddConstraint(
            model_name='productdesignplace',
            constraint=models.UniqueConstraint(fields=('product', 'place'), name='unique_product_place'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'viewName'), name='unique_product_viewName'),
        ),
    ]
