# Generated by Django 5.1 on 2026-08-06 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickeddesign',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DesignSession',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Design', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='design_sessions/')),
                ('designData', models.JSONField()),
                ('isTemplate', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedDesign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sourceType', models.CharField(choices=[('catalog', 'Catalog'), ('upload', 'Upload'), ('text', 'Text')], default='catalog', max_length=20)),
                ('uploadedImage', models.ImageField(blank=True, null=True, upload_to='uploaded_designs/')),
                ('croppedImage', models.ImageField(blank=True, null=True, upload_to='cropped_designs/')),
                ('text', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('horizontalFlip', models.BooleanField(default=False)),
                ('verticalFlip', models.BooleanField(default=False)),
                ('layer', models.IntegerField(default=1)),
                ('cropX', models.FloatField(default=0)),
                ('cropY', models.FloatField(default=0)),
                ('cropWidth', models.FloatField(default=1)),
                ('cropHeight', models.FloatField(default=1)),
                ('isBold', models.BooleanField(default=False)),
                ('isItalic', models.BooleanField(default=False)),
                ('textAlignment', models.CharField(default='center', max_length=20)),
                ('textShape', models.CharField(default='normal', max_length=30)),
                ('shapeIntensity', models.FloatField(default=0)),
                ('lineSpacing', models.FloatField(default=1)),
                ('outlineWidth', models.FloatField(default=0)),
                ('designColor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.vinylcolor')),
                ('fontFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.font')),
                ('outlineColor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.vinylcolor')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designplace')),
                ('sourceDesign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.design')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='base.designsession')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='designSession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designsession'),
        ),
        migrations.DeleteModel(
            name='DesignComponent',
        ),
    ]
