# Generated by Django 5.1 on 2026-08-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pickeddesign_user_designsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdesignplace',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
