# Generated by Django 5.1 on 2024-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_deliveredat_order_isdelivered_order_isready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
