# Generated by Django 5.1 on 2026-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_productdesignplace__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='font',
            constraint=models.UniqueConstraint(fields=('name', 'style'), name='unique_font'),
        ),
    ]
