# Generated by Django 5.1 on 2024-09-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
