# Generated by Django 5.1 on 2024-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_productcolorimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_product_viewName',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='viewName',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='make_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
