# Generated by Django 5.1 on 2026-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_font_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fonts/'),
        ),
    ]
