# Generated by Django 5.1 on 2024-09-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_designcategory_design_image_design_design_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='make_display',
        ),
        migrations.AddField(
            model_name='designcategory',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vinylcolor',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productcolorsize',
            name='size',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
