# Generated by Django 5.1 on 2024-10-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_productcolor_make_display_designcategory_show_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComponent',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(max_length=200, null=True)),
                ('width', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('center_x', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('center_y', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('is_color_changeable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productcolorimage',
            name='unique_product_color_viewName',
        ),
        migrations.RemoveConstraint(
            model_name='productdesignplace',
            name='unique_product_place',
        ),
        migrations.RemoveField(
            model_name='productcolorimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolorimage',
            name='viewName',
        ),
        migrations.RemoveField(
            model_name='productdesignplace',
            name='place',
        ),
        migrations.AddField(
            model_name='design',
            name='is_resizeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='max_colors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='design',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolor'),
        ),
        migrations.AddField(
            model_name='productcolorimage',
            name='designPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productdesignplace'),
        ),
        migrations.AddField(
            model_name='productdesignplace',
            name='viewName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdesignplace',
            name='x_end',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productdesignplace',
            name='x_start',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productdesignplace',
            name='y_end',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productdesignplace',
            name='y_start',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vinylcolor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proddesign',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolorimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productcolor'),
        ),
        migrations.AlterField(
            model_name='productcolorsize',
            name='countInStock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='productcolorimage',
            constraint=models.UniqueConstraint(fields=('color', 'designPlace'), name='unique_color_designPlace'),
        ),
        migrations.AddConstraint(
            model_name='productdesignplace',
            constraint=models.UniqueConstraint(fields=('product', 'viewName'), name='unique_product_viewName'),
        ),
        migrations.AddField(
            model_name='designcomponent',
            name='component_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productcolor'),
        ),
        migrations.AddField(
            model_name='designcomponent',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.design'),
        ),
        migrations.AddField(
            model_name='designcomponent',
            name='design_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.designtype'),
        ),
    ]
