# Generated by Django 5.1 on 2024-10-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_designcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='is_resizeable',
        ),
        migrations.RemoveField(
            model_name='design',
            name='max_colors',
        ),
        migrations.RemoveField(
            model_name='designcomponent',
            name='design_Type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='proddesign',
            name='designColor',
        ),
        migrations.AlterField(
            model_name='designcomponent',
            name='component_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vinylcolor'),
        ),
        migrations.AlterField(
            model_name='proddesign',
            name='design',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proddesign',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productdesignplace'),
        ),
    ]
