# Generated by Django 5.1 on 2024-10-10 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_design_is_resizeable_remove_design_max_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
