# Generated by Django 5.1 on 2024-10-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_productcolorimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='designPlace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productdesignplace'),
        ),
    ]
