# Generated by Django 5.1 on 2025-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_productcolorimage_designplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designcomponent',
            name='text',
        ),
    ]
